# Generated by Django 5.2.17 on 2026-08-24 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobrequisition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequisition',
            old_name='created_at',
            new_name='posted_date',
        ),
        migrations.RemoveField(
            model_name='jobrequisition',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(default='NEW', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('current_location', models.CharField(max_length=100)),
                ('current_company', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=50, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_note', models.TextField(blank=True, max_length=3500, null=True)),
                ('consent_data_accuracy', models.BooleanField(default=False)),
                ('consent_privacy_policy', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobrequisition')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(max_length=200)),
                ('year_of_passing', models.CharField(max_length=4)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working_here', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(blank=True, max_length=1000, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.application')),
            ],
        ),
    ]
