# Generated by Django 5.2.17 on 2026-08-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
